[package]
name = "nt_set_timer_resolution-rs"
version = "1.0.0"
edition = "2021"

[dependencies]
windows-dll = "0.3.0"

[target.'cfg(target_os="windows")'.build-dependencies]
winres = "^0.1"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
